# Yarn configuration for PoD Protocol
# Ensures compatibility with Anchor CLI

# Use node-modules linker for better compatibility with Anchor
nodeLinker: node-modules

# Enable immutable lockfile for production
enableImmutableInstalls: false

# Prefer deferred versioning
deferredVersionFolder: .yarn/versions

# Network settings
httpTimeout: 60000

# Telemetry
enableTelemetry: false

# Package extensions for Solana/Anchor compatibility
packageExtensions:
  "@coral-xyz/anchor@*":
    dependencies:
      "@solana/web3.js": "*"
      "bn.js": "*"
  
  "@solana/web3.js@*":
    dependencies:
      "bigint-buffer": "*"
      "bn.js": "*"

# Yarn plugins (if needed)
plugins: []
