title: "🧪 Beta Testing Feedback: "
labels: ["beta-testing", "feedback"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for participating in the PoD Protocol Beta Program! Your feedback is invaluable.

  - type: dropdown
    id: testing_area
    attributes:
      label: "Testing Area"
      description: "What aspect of PoD Protocol did you test?"
      options:
        - Agent Registration & Management
        - Direct Messaging
        - Channel Communication
        - Escrow System
        - Rate Limiting
        - ZK Compression (Experimental)
        - CLI Tools
        - SDK Integration
        - Documentation
        - Performance
        - Security
        - Other
    validations:
      required: true

  - type: dropdown
    id: overall_experience
    attributes:
      label: "Overall Experience"
      description: "How was your overall testing experience?"
      options:
        - Excellent - Everything worked smoothly
        - Good - Minor issues encountered
        - Fair - Some significant issues
        - Poor - Major problems encountered
    validations:
      required: true

  - type: textarea
    id: what_worked
    attributes:
      label: "What Worked Well"
      description: "What aspects of PoD Protocol worked as expected?"
      placeholder: "The following features worked well..."
    validations:
      required: true

  - type: textarea
    id: issues_encountered
    attributes:
      label: "Issues Encountered"
      description: "What problems, bugs, or unexpected behaviors did you encounter?"
      placeholder: "I encountered the following issues..."
    validations:
      required: false

  - type: textarea
    id: improvement_suggestions
    attributes:
      label: "Improvement Suggestions"
      description: "How could PoD Protocol be improved?"
      placeholder: "I suggest improving..."
    validations:
      required: false

  - type: textarea
    id: use_case
    attributes:
      label: "Your Use Case"
      description: "What were you trying to build or accomplish?"
      placeholder: "I was testing PoD Protocol for..."
    validations:
      required: true

  - type: dropdown
    id: likelihood_to_use
    attributes:
      label: "Likelihood to Use in Production"
      description: "How likely are you to use PoD Protocol in production?"
      options:
        - Very Likely - Already planning integration
        - Likely - Would use after some improvements
        - Possibly - Depends on future development
        - Unlikely - Doesn't meet current needs
    validations:
      required: true

  - type: textarea
    id: missing_features
    attributes:
      label: "Missing Features"
      description: "What features are missing that you need for your use case?"
      placeholder: "I need the following features..."
    validations:
      required: false

  - type: textarea
    id: documentation_feedback
    attributes:
      label: "Documentation Feedback"
      description: "How was the documentation? What could be improved?"
      placeholder: "The documentation was..."
    validations:
      required: false

  - type: textarea
    id: additional_feedback
    attributes:
      label: "Additional Feedback"
      description: "Any other feedback, suggestions, or comments?"
      placeholder: "Additional feedback..."
    validations:
      required: false