title: "💡 Feature Idea: "
labels: ["enhancement", "community-idea"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing an idea to improve PoD Protocol! This template helps us understand your suggestion better.

  - type: textarea
    id: problem
    attributes:
      label: "Problem Statement"
      description: "What problem does this feature solve? What's the current limitation or pain point?"
      placeholder: "Currently, it's difficult to..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: "Proposed Solution"
      description: "Describe your proposed solution in detail."
      placeholder: "I suggest implementing..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: "Alternative Solutions"
      description: "What other approaches have you considered?"
      placeholder: "Alternatively, we could..."
    validations:
      required: false

  - type: dropdown
    id: component
    attributes:
      label: "Component"
      description: "Which part of PoD Protocol does this relate to?"
      options:
        - Core Protocol (Solana Program)
        - TypeScript SDK
        - CLI Tools
        - Documentation
        - ZK Compression
        - IPFS Integration
        - Analytics
        - Security
        - Performance
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      description: "How important is this feature to you?"
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for adoption
        - Critical - Blocking my use case
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: "Additional Context"
      description: "Any additional information, mockups, or examples that might help?"
      placeholder: "Additional context..."
    validations:
      required: false