name: 🐛 Bug Report
description: Report a bug or unexpected behavior in PoD Protocol
title: "[BUG] "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! This helps us improve PoD Protocol for everyone.
        
        **For security vulnerabilities:** Please email security@pod-protocol.com instead of creating a public issue.

  - type: checkboxes
    id: terms
    attributes:
      label: "Pre-submission Checklist"
      description: "Please confirm you've completed these steps:"
      options:
        - label: "I've searched existing issues and this isn't a duplicate"
          required: true
        - label: "I've read the documentation and troubleshooting guide"
          required: true
        - label: "I'm using a supported version (check releases)"
          required: true

  - type: dropdown
    id: component
    attributes:
      label: "Component"
      description: "Which component is affected?"
      options:
        - Core Protocol (Solana Program)
        - TypeScript SDK
        - CLI Tools
        - ZK Compression
        - IPFS Integration
        - Documentation
        - Examples
        - Tests
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: "Severity"
      description: "How severe is this bug?"
      options:
        - Low - Minor inconvenience
        - Medium - Significant impact
        - High - Major functionality broken
        - Critical - Security issue or protocol failure
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "Bug Description"
      description: "A clear and concise description of the bug."
      placeholder: "When I try to..., I expect..., but instead..."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: "Steps to Reproduce"
      description: "Detailed steps to reproduce the bug."
      placeholder: |
        1. Initialize client with...
        2. Call function...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Expected Behavior"
      description: "What should happen instead?"
      placeholder: "I expected..."
    validations:
      required: true

  - type: dropdown
    id: network
    attributes:
      label: "Network"
      description: "Which Solana network are you using?"
      options:
        - Devnet
        - Testnet
        - Mainnet
        - Localnet
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: "Environment"
      description: "Please provide your environment details."
      placeholder: |
        - OS: [e.g., macOS 12.0, Ubuntu 20.04]
        - Node.js version: [e.g., 18.17.0]
        - PoD Protocol version: [e.g., 1.0.0]
        - Solana CLI version: [e.g., 1.16.0]
        - Rust version: [e.g., 1.70.0]
      render: markdown
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: "Error Logs"
      description: "Include relevant error messages, stack traces, or transaction signatures."
      placeholder: "Paste error logs here..."
      render: shell
    validations:
      required: false

  - type: input
    id: contact
    attributes:
      label: Contact Details (Optional)
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com or Discord username
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: "Additional Context"
      description: "Any other relevant information, screenshots, or context."
      placeholder: "Additional context..."
    validations:
      required: false