name: ✨ Feature Request
description: Suggest a new feature or enhancement for PoD Protocol
title: "[FEATURE] "
labels: ["enhancement", "feature-request"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Your ideas help make PoD Protocol better.

  - type: checkboxes
    id: checklist
    attributes:
      label: "Pre-submission Checklist"
      description: "Please confirm you've completed these steps:"
      options:
        - label: "I've searched existing issues and discussions"
          required: true
        - label: "I've read the roadmap and this isn't already planned"
          required: true
        - label: "This feature aligns with PoD Protocol's goals"
          required: true

  - type: textarea
    id: problem
    attributes:
      label: "Problem Statement"
      description: "What problem does this feature solve? What's the current limitation?"
      placeholder: "Currently, it's difficult to... because..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: "Proposed Solution"
      description: "Describe your proposed solution in detail."
      placeholder: "I suggest implementing..."
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: "Component"
      description: "Which part of PoD Protocol would this affect?"
      options:
        - Core Protocol (Solana Program)
        - TypeScript SDK
        - CLI Tools
        - ZK Compression
        - IPFS Integration
        - Analytics
        - Documentation
        - Examples
        - Security
        - Performance
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      description: "How important is this feature?"
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for adoption
        - Critical - Blocking use case
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: "Alternative Solutions"
      description: "What other approaches have you considered?"
      placeholder: "Alternatively, we could..."
    validations:
      required: false

  - type: textarea
    id: use_cases
    attributes:
      label: "Use Cases"
      description: "Describe specific use cases where this feature would be valuable."
      placeholder: "This would help when..."
    validations:
      required: true

  - type: textarea
    id: technical_details
    attributes:
      label: "Technical Details"
      description: "Any technical considerations, API design ideas, or implementation thoughts?"
      placeholder: "Technical implementation could involve..."
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: "Additional Context"
      description: "Any additional information, mockups, links, or examples?"
      placeholder: "Additional context..."
    validations:
      required: false