[package]
name = "pod-com"
version = "0.1.0"
description = "PoD Protocol (Prompt or Die): AI Agent Communication Protocol"
edition = "2021"
rust-version = "1.86"

[lib]
crate-type = ["cdylib", "lib"]
name = "pod_com"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
idl-build = ["anchor-lang/idl-build"]
anchor-debug = []
no-log-ix-name = []

[dependencies]
anchor-lang = "0.31.1"
anchor-spl = "0.31.1"
solana-program = "1.18.22"
solana-sdk = "1.18.22"
light-sdk = "0.13.0"
anyhow = "1.0.71"

# Spl dependencies (commented out as they're optional)
# spl-token = { version = "=4.0.0", optional = true, default-features = false }
# spl-associated-token-account = { version = "=2.0.0", optional = true, default-features = false }

# Serialization - using the one from anchor-lang to avoid conflicts
# borsh = { version = "=1.5.7" }
# borsh-derive = "=0.10.3"

# Error handling
thiserror = "=2.0.12"

# Explicitly disable any features that might pull in getrandom/rand
[package.metadata.docs.rs]
all-features = false
no-default-features = true

[dev-dependencies]
anchor-lang = { version = "0.31.1", features = ["derive"] }
# Test dependencies can be added here if needed
